SCHEMA = [
    'date',
    'employee_title',
    'location',
    'employee_status',
    'review_title',
    'experience',
    'helpful',
    'pros',
    'cons',
    'advice_to_mgmt',
    'rating_overall',
    'rating_balance',
    'rating_culture',
    'rating_career',
    'rating_comp',
    'rating_mgmt',
]
